"""empty message

Revision ID: e5a1afd56699
Revises: 2d8735e5b245
Create Date: 2022-11-07 15:33:01.498161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a1afd56699'
down_revision = '2d8735e5b245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rest_name', sa.String(length=120), nullable=False),
    sa.Column('rest_address', sa.String(length=80), nullable=False),
    sa.Column('rest_image', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rest_name')
    )
    op.create_table('review_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rest_name', sa.String(length=120), nullable=False),
    sa.Column('review', sa.String(length=300), nullable=False),
    sa.Column('rating', sa.String(length=300), nullable=False),
    sa.Column('rest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rest_id'], ['restaurant_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rest_name')
    )
    op.drop_table('restaurant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rest_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('rest_address', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rest_image', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='restaurant_pkey'),
    sa.UniqueConstraint('rest_name', name='restaurant_rest_name_key')
    )
    op.drop_table('review_table')
    op.drop_table('restaurant_table')
    # ### end Alembic commands ###
